FROM ubuntu:14.04
MAINTAINER Calin Groza "https://github.com/flowidcom/calypso"
RUN apt-get update
RUN apt-get install -y nginx
RUN apt-get install -y wget
RUN echo "Calypso Web Application" > /usr/share/nginx/html/index.html
EXPOSE 80
